volumes:
    db:
    nextcloud:

services:
    db:
        image: postgres
        restart: no
        env_file:
            - ./.env.postgres
        volumes:
            - db:/var/lib/postgresql/data

    app:
        image: nextcloud
        restart: no
        ports:
            - 8194:80
        env_file:
            - ./.env.nextcloud
            - ./.env.postgres
        volumes:
            - nextcloud:/var/www/html
        depends_on:
            - db
